### ISSUE TITLE
Adjusted WoE

### ISSUE THREAD

**Issue by hbg26** [ShichenXie/scorecard#1]
First of all, thank you for your useful package. I have a question: I don't quite understand what kind of adjustment the function woebin applies when there is a zero frequency class in a category?.  I mean How woe's are calculated then?

**Comment by ShichenXie** [comment]
WOE is defined as $WeightofEvidence = \ln(\frac{DistributionBad_{i}}{DistributionGood_{i}})$, where $DistributionBad_{i} = \frac{Bad_{i}}{\sum(Bad_{i})}$ and $DistributionGood_{i} = \frac{Good_{i}}{\sum(Good_{i})}$.   

If there is a zero frequency, which means $DistributionBad_{i} = 0$ or $DistributionGood_{i} = 0$ in the above equation, the zero $Bad_{i} or Good_{I}$ will replaced by 0.9. Therefore, the zero frequency class is avoided via a very small number.
