### ISSUE TITLE
`perf_eva()` function is very slow

### ISSUE THREAD

**Issue by Leo-Lee15** [ShichenXie/scorecard#10]
Hello,

I've found the `perf_eva()` function very slow with big dataset. Maybe it would be better to extract the `show_plot` arguement from `perf_eva()` function and write a generic `plot.*`  function to do the plot part?

Thanks!

**Comment by ShichenXie** [comment]
Hi,
You can specify `groupnum` a integer like 100, otherwise `perf_eva` will plot every point of you dataset.

**Comment by Leo-Lee15** [comment]
Thanks for pointing out that! I've tried and the speed is much better.
