### ISSUE TITLE
Automated variable selection considering highly correlated variables

### ISSUE THREAD

**Issue by hope-data-science** [ShichenXie/scorecard#12]
VIF had been included as a function in the scorecard package, why not include it in the var_filter to filter out  
the hight correlated variables(assume all the variables are numeric)? Another way might be using caret::findCorrelation to do the filter work.

**Comment by ShichenXie** [comment]
1. `var_filter` should be able to handle categorical variables. 
2. If there are hundreds/thousands features, the process would be very slow when considering correlation in the `var_filter` function.

In my experience,  the `vif` function is adopted to measure the correlation only after lasso or stepwise when there are only few features left.
