### ISSUE TITLE
a bug in woebin ?

### ISSUE THREAD

**Issue by armgong** [ShichenXie/scorecard#13]
today using woebin to bin a factor variable  but the result is strange
~~~R
pflag<-rep(0,12278)
cus_cus_class<-rep("1",12278)

pflag1<-rep(1,241213)
cus_cus_class1<-rep("1",241213)

pflag2<-rep(0,3646)
cus_cus_class2<-rep("3",3646)

pflag3<-rep(1,1762)
cus_cus_class3<-rep("3",1762)

pflagall<-c(pflag,pflag1,pflag2,pflag3)
cus_cus_classall<-c(cus_cus_class,cus_cus_class1,cus_cus_class2,cus_cus_class3)

cus_cus_classall<-as.factor(cus_cus_classall)

df=data.frame(pflagall,cus_cus_classall)

table(df)


library(scorecard)
library(smbinning)

iv(df,"pflagall","cus_cus_classall")

woebin(df,"pflagall","cus_cus_classall")

smbinning.factor(df,"pflagall","cus_cus_classall")$ivtable
~~~

the result of iv and smbinning is 0.84 , but woebin can't even binning .

**Comment by armgong** [comment]
~~~R
>iv(df,"pflagall","cus_cus_classall")
           variable info_value
1: cus_cus_classall  0.8214501

> woebin(df,"pflagall","cus_cus_classall")
[INFO] creating woe binning ... 
$cus_cus_classall
           variable   bin  count count_distr  good    bad   badprob woe bin_iv total_iv breaks is_special_values
1: cus_cus_classall 1%,%3 258899           1 15924 242975 0.9384934   0      0        0  1%,%3             FALSE

>smbinning.factor(df,"pflagall","cus_cus_classall")$ivtable  

 Cutpoint CntRec CntGood CntBad CntCumRec CntCumGood CntCumBad PctRec GoodRate BadRate    Odds  LnOdds     WoE

1    = '1' 253491  241213  12278    253491     241213     12278 0.9791   0.9516  0.0484 19.6460  2.9779  0.2527 

2    = '3'   5408    1762   3646    258899     242975     15924 0.0209   0.3258  0.6742  0.4833 -0.7272 -3.4523 
3  Missing      0       0      0    258899     242975     15924 0.0000      NaN     NaN     NaN     NaN     NaN 

4    Total 258899  242975  15924        NA         NA        NA 1.0000   0.9385  0.0615 15.2584  2.7251  0.0000    
IV 
1 0.0560 
2 0.7654
3   NaN 
4 0.8214
--
 
  |  
 


~~~~

**Comment by armgong** [comment]
ok set count_distr_limit=0.01 solve this ,thanks

**Comment by ShichenXie** [comment]
To make a robust model or stable woe values , each bin should not contains too less observations. A  5% is recommended usually as the minimum count distribution rate .

**Comment by armgong** [comment]
but this variable is indeed a very strong indicator of  real business ,so set it to 0.01 is a tradeoff.
a off-topic question 

using woebin on a dataset (row num is  250000 col num is 309)  on windows server 2016 ,it has 48 core 96 threads.
run time of  woebin with no_cores 2 4 6 8  no difference ,  6-7 mins .
is this normal？Windows task manager show background r process started，but runtime always same

**Comment by ShichenXie** [comment]
What about 2 and 20 cores? 
In my experience, the more cores used, should be the less running time. The parallel calculation effects when you have many features, like thousands of columns. Your dataset seems not so big in columns.

This package depends on data.table, which might do some parallel calculation on the backend. I'm not sure is this related.

**Comment by armgong** [comment]
bad luck ,use 20 cores still same time, now data is 260000 rows, 602 columns, runtime of 8 core is 13 mins ,20 cores is also 13 mins.

**Comment by ShichenXie** [comment]
It seems OK on Macbook Pro 2017. 

The issue in your computer might be due to the setting of OpenBLAS package. You can read the posts in [Parallel processing in R limited](https://stackoverflow.com/questions/12924698/parallel-processing-in-r-limited).  Actually, I don't understand it fully. Try to figure out by yourself if you have time. 

```r
library(scorecard)
system.time(a <- woebin(germancredit, 'creditability', print_info=FALSE, no_cores = 1))
system.time(b <- woebin(germancredit, 'creditability', print_info=FALSE, no_cores = 2))
```
![screen shot 2019-01-10 at 9 30 08 pm](https://user-images.githubusercontent.com/15758951/50971535-33477000-151f-11e9-8e0e-cbe65a8229ad.png)

**Comment by armgong** [comment]
Thanks a lot , my r use basic blas ,not openblas ,My guess is r parallel packages malfunction on windows.
I will try to figure it out if I have time. 
Thank you for wonderful package
