### ISSUE TITLE
perf_eva() is not working in scorecard version 0.2.2

### ISSUE THREAD

**Issue by timotiusnico** [ShichenXie/scorecard#14]
Hi,

Thanks for publishing the package. I'm recently trying to run your example code in the github page using R3.3.3. However, when the package is executing perf_eva, i got an error shown below

Error in perf_eva(pred = pred_list, label = label_list) : 
  could not find function "isFALSE"

Is there any workaround about it?

My env is as follows

R3.3.3
data.table 1.10.4-3
ggplot2 3.0.0
gridExtra 2.3
foreach 1.4.4
doParallel 1.0.14
parallel 3.3.3
openxlsx 4.0.17

Thanks

**Comment by ShichenXie** [comment]
`isFALSE` is a base function, but only available after R3.5.  I have replaced the `!isFalse(x)` with `isTRUE(x) & !is.null(x)`, which should be fine for older version R. 
1. You can update R to the latest version, or
2. install the latest version of package from GitHub via `devtools::install_github('shichenxie/scorecard')`

**Comment by timotiusnico** [comment]
Thanks for the response, mate :)
