### ISSUE TITLE
A suggestion on the `report()` function

### ISSUE THREAD

**Issue by Leo-Lee15** [ShichenXie/scorecard#15]
Hi,  

I've used the newly-added `report()` function, which is awesome! Thanks for the nice work.

But I'am a little confused about the results of the function in the [`Example II`](http://shichen.name/scorecard/reference/report.html) in your pkgdown website.

```r
# Example II
# input dt is a list
# multiple datasets
report(list(dt1=germancredit[sample(1000,500)],
            dt2=germancredit[sample(1000,500)],
            dt3=germancredit[sample(1000,500)]), y, x,
 breaks_list, special_values, seed=NULL, save_report='report5')
```
The `model coefficients` sheet in the results only contains one model as the following table shows.

Model coefficients based on dt1 dataset |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
variable | Estimate | Std. Error | z value | Pr(>\|z\|) | gvif | info_value | missing_rate
(Intercept) | -0.881272674 | 0.1215 | -7.2541 | 0 |   |   |  
age.in.years_woe | 0.668220936 | 0.2807 | 2.3806 | 0.0173 | 1.1049 | 0.22 | 0
credit.amount_woe | 0.967266281 | 0.3634 | 2.6614 | 0.0078 | 1.0981 | 0.114 | 0
credit.history_woe | 0.757056585 | 0.246 | 3.0779 | 0.0021 | 1.0486 | 0.2446 | 0
duration.in.month_woe | 1.099128399 | 0.3058 | 3.5943 | 0.0003 | 1.1218 | 0.1909 | 0
housing_woe | 0.643615146 | 0.3308 | 1.9454 | 0.0517 | 1.1837 | 0.1448 | 0
installment.rate.in.percentage.of.disposable.income_woe | 3.036753444 | 1.185 | 2.5627 | 0.0104 | 1.0749 | 0.0112 | 0
other.installment.plans_woe | 1.09219108 | 0.9865 | 1.1071 | 0.2682 | 1.0651 | 0.0138 | 0
personal.status.and.sex_woe | 0.891955405 | 0.3022 | 2.9514 | 0.0032 | 1.1737 | 0.173 | 0
present.employment.since_woe | 0.500596126 | 0.3533 | 1.4171 | 0.1565 | 1.0975 | 0.116 | 0
property_woe | -0.026460202 | 0.5042 | -0.0525 | 0.9581 | 1.2567 | 0.066 | 0
purpose_woe | 1.099060268 | 0.3181 | 3.4549 | 0.0006 | 1.0602 | 0.1507 | 0
savings.account.and.bonds_woe | 0.815971484 | 0.3136 | 2.6017 | 0.0093 | 1.0375 | 0.1591 | 0
status.of.existing.checking.account_woe | 0.835177462 | 0.1528 | 5.4651 | 0 | 1.0402 | 0.6804 | 0

Based on the above result, we can infer that the model is based on the `dt1` data. The other two dataset are based on the __glm__ model of `dt1` data.  We can consider the `dt1` dataset as the train set, `dt2` as the test set and `dt3` as the out of time sample (although it is not). 

 Am I right? If so, I would advize you to point out it in the function's documentation. For example, 

>  dt  A data frame with both x (predictor/feature) and y (response/label) variables; or a list of dataframes. If a list of dataframes provided, only the first dataframe would be used for training. Other dataframes would be used for testing. 

Thanks again for this awesome package!

**Comment by Leo-Lee15** [comment]
Besides, I've found there is a typo in the performance plots in the `perf_eva()` function.  Take the following screenshot for example,
![image](https://user-images.githubusercontent.com/18102092/51440926-0bb68b80-1d07-11e9-8a34-6e8591391845.png)

As can be seen from the ROC plot, there is a typo.  The text should be `AUC` instead of `KS`. Hope this can be fixed soon. 
 
I'm also confused about the values in the brackets. I know that `p = 0.2599` is the threshold, but what does the `(0.54, 0.52)` (in the KS plot) mean?

The code is 
```r
data("germancredit")
dt_f <- var_filter(germancredit, "creditability")
dt_list <- split_df(dt_f, "creditability")
label_list <- lapply(dt_list, function(x) x$creditability)
bins <- woebin(dt_list$train, "creditability")
dt_woe_list <- lapply(dt_list, function(x) woebin_ply(x, bins))
m1 <- glm(creditability ~ ., family = binomial(), data = dt_woe_list$train)
m_step <- step(m1, direction = "both", trace = FALSE)
m2 <- eval(m_step$call)
pred_list <- lapply(dt_woe_list, function(x) predict(m2, type = "response", x))
perf_eva(pred = pred_list$train, label = dt_list$train$creditability, title = "train")
```

**Comment by ShichenXie** [comment]
1. I have update the document of `report` function according to your suggestion. Thanks. 
2. `(0.54, 0.52)`refers to the coordinate of the red point on KS plot. The typo has been fixed in few days ago. 

Try to install the latest version of package from github via `devtools::install_github('shichenxie/scorecard')`

**Comment by Leo-Lee15** [comment]
Awesome!
