### ISSUE TITLE
 'tree' and 'chimerge' binning issue for binary numeric variable

### ISSUE THREAD

**Issue by KingsleyW** [ShichenXie/scorecard#21]
If the numeric variable only contains two values, it will not output the correct bin when doing  'tree' and 'chimerge' binning. But 'width' and 'freq' binning work well. 

`tst_dt <- data.table(var = c(rep(10, 20), rep(20, 10)), target = c(sample(c(0,1), 30, replace = TRUE)))
tree_bins = woebin(tst_dt, y = 'target', x = 'var', positive = "1", method = 'tree')
chi_bins = woebin(tst_dt, y = 'target', x = 'var', positive = "1", method = 'chimerge')
width_bins = woebin(tst_dt, y = 'target', x = 'var', positive = "1", method = 'width')
freq_bins = woebin(tst_dt, y = 'target', x = 'var', positive = "1", method = 'freq')`

From the source code, 'tree' and 'chimerge' binning will call the function 'woebin2_init_bin'.
The following code from this function drops the value of this binary variable. So that causes only one bin [-Inf, Inf]. 
`brk = sort(brk[(brk < max(xvalue, na.rm =TRUE)) & (brk > min(xvalue, na.rm =TRUE))])`

Please review.

**Comment by ShichenXie** [comment]
Thanks. The bug has been fixed, see the latest version on GitHub.
