### ISSUE TITLE
function rmcol_datetime_unique1 suppose dt must have a character col

### ISSUE THREAD

**Issue by longhua8800w** [ShichenXie/scorecard#22]
when i use package scorecard which is a great tool to use, i encounter an error 
"Error in matrix(unlist(value, recursive = FALSE, use.names = FALSE), nrow = nr,  : 
  'data' must be of a vector type, was 'NULL'"
when i am binning var use  woebin()  or  woebin_ply().
i dive into it found that  in internal function rmcol_datetime_unique1() , it suppose dt must have a character col,which is not the condition in my work.

**Comment by ShichenXie** [comment]
please provides a sample data to reproduce your error.

**Comment by ShichenXie** [comment]
下面的例子就是只有数值特征，并没有问题。你可以做的是先升级到github上面的最新版再试试。如果还碰到问题，提供可以可重现的案例，包括数据和代码。

```r
library(data.table)
library(scorecard)

dt = setDT(list(x=sample(1:6, 50, replace = TRUE),
                y=sample(0:1, 50, replace = TRUE)))
woebin(dt, 'y')
```
