### ISSUE TITLE
Can the console outputs when using graphics (such as woebin_plot & perf_eva) be suppressed? 

### ISSUE THREAD

**Issue by Sean-Sexton** [ShichenXie/scorecard#24]
This is particularly an issue when using the scorecard function in RMarkdown chunks and document generating. Is there a way to suppress all outputs when using graphics? An example would be when using the woebin_plot() function, there will be a printed `## $variable`  line in the R Markdown (or console in R) which I would like to remove. Similarly, with perf_eva, there are a few lines of console output I would like to suppress. Is there an option that will only output the graph?

**Comment by ShichenXie** [comment]
Try unlist function.
