### ISSUE TITLE
including frequency weights

### ISSUE THREAD

**Issue by Percayso-Neil** [ShichenXie/scorecard#25]
Hi, useful package.  Are there any plans to include frequency weights throughout the package?  i.e. where the data is a sample taken from a large population (say 1 in 2 bads and 1 in 10 goods) and as such the data contains a weight field, containing 2 (for bads) or 10 (for goods).  The weights should influence the binning, woe calculations and glm processes.  However this may causes issues with glm, which can have issues with weights, and therefore the package may need to be adapted to use svyglm.  thanks.

**Comment by ShichenXie** [comment]
It seems both glm and svyglm with weights have the same estimated parameters. See this [website](https://stats.stackexchange.com/questions/57107/use-of-weights-in-svyglm-vs-glm).
