### ISSUE TITLE
like this program.  but i do not see traditional woe graphs  for variables.   that is, the woe for each bin,  bins on the x-axis and the WOE on the y-axis.  those quick visuals are very useful for analysis.

### ISSUE THREAD

**Issue by kevinoden** [ShichenXie/scorecard#27]

**Comment by ShichenXie** [comment]
Good point. I will add this feature.

**Comment by kevinoden** [comment]
looking forward to utilizing it.

**Comment by ShichenXie** [comment]
See the latest commit (https://github.com/ShichenXie/scorecard/commit/9c486819e86434f354bc5ee80e5f3d1f15d9c137). You can update it via `devtools::install_github('shichenxie/scorecard')`
