### ISSUE TITLE
Scaling for "Good" model

### ISSUE THREAD

**Issue by ngyongkad** [ShichenXie/scorecard#28]
Hi, 

Can I confirm one thing? 

If I want to generate a scorecard that predict 'good' (i.e. the positive is 'good'), the scaling formula (i.e. score = A - B*ln(odd)) embedded will not be correct.

Any knows a work around?  Thanks.   

************************************************************************

I figured out the work around.

**Comment by ShichenXie** [comment]
share it with us :)

**Comment by ngyongkad** [comment]
Just need to set the PDO as a negative value and set the base odd in terms of good/bad odd .  :)
