### ISSUE TITLE
Bug in `germancredit` data

### ISSUE THREAD

**Issue by ugroempi** [ShichenXie/scorecard#31]
Hi Shichen,
for the factor `personal.status.and.sex`, I find that the `germancredit` data erroneously classifies all cases from the factor level `male : divorced/separated` as `female : divorced/separated/married`. The `female : single` category appears to be indeed empty even in the original data, but the `male : divorced/separated` category is not.
Best, Ulrike

**Comment by ShichenXie** [comment]
Thanks. The bug has been fixed (https://github.com/ShichenXie/scorecard/commit/16867d08f3c827ccf39d43286e541c54368cead1).
