### ISSUE TITLE
report function error

### ISSUE THREAD

**Issue by mrmelchi** [ShichenXie/scorecard#32]
I have been using scorecard for any time, it is excellent, but yesterday I ran a R program that I run monthly and  give the following error:

```
report(list(train = dt_list$train, test = dt_list$test), y = 'Reclasificado',
                         x = cols_not_remove, breaks_list = breaks_adj, special_values = NULL,
                         seed = seed,  save_report='report1', show_plot = c('ks', 'lift', 'gain',
                         'roc', 'lz', 'pr', 'f1', 'density'),
                         bin_type = 'width')
```
[INFO] sheet1-dataset information
[INFO] sheet2-model coefficients
[INFO] sheet3-model performance
[INFO] sheet4-variable woe binning
[INFO] sheet5-scorecard
[INFO] sheet6-population stability
Error in setnames(psi_tbl, gains_table_cols) : 
Can't assign 12 names to a 13 column data.table

Thank you in advance.

**Comment by ShichenXie** [comment]
Sorry, It is a bug. Please use the previous version of package.

**Comment by ShichenXie** [comment]
I have fixed the bug. You can install the latest version of package from GitHub via ```devtools::install_github("shichenxie/scorecard")```.
