### ISSUE TITLE
Merge `missing` bin with few counts with another bin

### ISSUE THREAD

**Issue by jbkunst** [ShichenXie/scorecard#33]
Hi Shichen,

Thanks so much for your package and all your time and work in it!

Is there any way in `woebin` or other function to merge a missing category (`NA` values) with very less counts (`< count_distr_limit`) in a category with relative same `badprob`?

For example I would like to merge the `missing` bin with `[0.54,0.8)` (the 4th one) due have similiar bad rates.

``` r
set.seed(123)

N <- 1000
p <- runif(N)
y <- rbinom(N, 1, p)

p[runif(N) < 0.01] <- NA

scorecard::woebin(data.frame(p, y), y = "y")
#> [INFO] creating woe binning ...
#> $p
#>    variable         bin count count_distr good bad    badprob        woe
#> 1:        p     missing     7       0.007    2   5 0.71428571  0.8362480
#> 2:        p [-Inf,0.14)   139       0.139  133   6 0.04316547 -3.1786324
#> 3:        p [0.14,0.54)   403       0.403  253 150 0.37220844 -0.6027969
#> 4:        p  [0.54,0.8)   254       0.254   75 179 0.70472441  0.7898550
#> 5:        p  [0.8,0.94)   137       0.137   15 122 0.89051095  2.0159281
#> 6:        p [0.94, Inf)    60       0.060    2  58 0.96666667  3.2872531
#>        bin_iv total_iv  breaks is_special_values
#> 1: 0.00455648 1.903872 missing              TRUE
#> 2: 0.84406952 1.903872    0.14             FALSE
#> 3: 0.14384048 1.903872    0.54             FALSE
#> 4: 0.14847755 1.903872     0.8             FALSE
#> 5: 0.40997000 1.903872    0.94             FALSE
#> 6: 0.35295827 1.903872     Inf             FALSE
```

<sup>Created on 2019-12-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks in advance for your response.

cc @jm448

**Comment by ShichenXie** [comment]
I don’t known how to merge it automatically, since the missing is a separated bin by default. 

There are two ways to fix this issue manually. 1st, make missing imputation, see the replace_na function. 2nd, using woebin_adj function manually adjust the binnng breaks.

**Comment by ShichenXie** [comment]
I hope the last post solved your problem. I close this issue now.
