### ISSUE TITLE
Error for some outcome levels

### ISSUE THREAD

**Issue by ptlarsson** [ShichenXie/scorecard#34]
If the positive outcome is other than "bad" or 1 and the positive option is used to define it, you can get an error under some condition when using woebin.   For example, if levels are are "bad" and "not bad" instead of "bad" and "good"  the code will fail as the recoding uses string match and every record gets coded as 1 in this example.

Also it would be nice if the WOE tables and plots would reflect the levels of the dependent variable as labeling everything as good or bad does not always make sense.  For example, I use scorecard for marketing and the positive outcome is a response so would be nice to be able to label the plats and tables accordingly. 

Love your package, find it very useful.

Tomas

**Comment by ShichenXie** [comment]
Good points. I have fixed the first issue. Please install the version on Github and try again. Since there are too many 'good'/'bad' in the scripts, I have only replace the good/bad by negative/positive in KS plot. I'll modified it in the future. Thanks.
