### ISSUE TITLE
Diffrence in woebin using v.2.9 and v.2.8.1

### ISSUE THREAD

**Issue by bomanv** [ShichenXie/scorecard#37]
I try to use this package when building a scorecard. But when using different version of the package I get different binning and IV using the woebin function. I can´t see any changes in the release notes for the different versions.

**Comment by jbkunst** [comment]
Same here. It would be useful know that. Thanks in advance.

**Comment by ShichenXie** [comment]
Sorry, I changed the way to create initial fine binning in V0.2.9, which might inappropriate. I have modified it again, see https://github.com/ShichenXie/scorecard/blob/4d05be6b6eff3223c045c8708f76bffc2b3eb541/R/woebin.R#L240. You can install the latest version on github. I will upload to CRAN when I get your feedback.

**Comment by bomanv** [comment]
Hi,

thanks for answering. But for clarification you have reversed the changes back to v.2.8.1 in the new unpublished package?

**Comment by ShichenXie** [comment]
No, they are not exactly the same. The unpublished version supports to binning for numeric variables in same case that v.2.8.1 might not be able to. You can make a comparison.
