### ISSUE TITLE
单行数据 woe替换慢

### ISSUE THREAD

**Issue by longhua8800w** [ShichenXie/scorecard#39]
您好，我想把开发的评分卡直接上线到生产的R服务，但发现单行数据的woe替换速度太慢要1.5秒左右，这是不能满足直接上线需求的。 下面是示例 只有 7个变量 一行数据。耗时1.39秒。 我可以手写这个替换步骤让它单行替换耗时下降到几十毫秒。但还是希望这能成为这个优秀包的特性。不知道是否可行。
> woebin_ply(input,sc$bins)%>%rename_all(~.x%>%str_remove("_woe"))
[INFO] converting into woe values ... 
   no als_m12_cell_nbank_finlea_orgnum als_m3_id_nbank_cf_orgnum r_m01_cell_pdl_0allnumorgnum r_m03_id_caon_0allnumorgnum
1:  1                       0.05253662                -0.2286684                 -0.006342389                  -0.1508286
   r_m12_cell_0sloannbank_allnum r_m12_cell_nbank_0weekall_allnum r_m12_id_0avgmax_monnum
1:                   -0.06246272                        -0.112977              -0.4454012
> system.time( woebin_ply(input,sc$bins)%>%rename_all(~.x%>%str_remove("_woe")))
[INFO] converting into woe values ... 
用户 系统 流逝 
0.00 0.02 1.39

**Comment by ShichenXie** [comment]
评分卡部署时不需要转换woe，可以基于scorecard用scorecard_ply将变量原值转成对应得分。

**Comment by longhua8800w** [comment]
是这样的，但是我的分箱是用sas做的，公司惯用的做法是sas 用同一组cuts在 train test（实际是valid）上分箱，保持train test 上有一致的单调 趋势，并与业务含义一致，这个在scorecard里目前还是没有sas9.1上方便，其他方面sas都很不方便，所以我把sas分箱代码的结果 用R翻译成与scorecard包 bins相同的格式。但是，目前公司用的sas宏评分 跟scorecard里评分不一致（sas 的woe默认y=0是分子，scorecard里默认1是分子，而且我看了sas宏 和 scorecard源码差别还不止这些，不是改了这个选项就可以的，暂时没时间把这种差异搞清楚），所以我只能，自己把公司用的sas宏里的打分逻辑在R里实现一遍，所以暂时不能用scorecard_ply。 也许这是个临时性的特殊需求。

**Comment by ShichenXie** [comment]
- woebin设置break_list就可以很方便的把切割点统一的啊，不知道你说的sas方便在哪；
- scorecard也可以通过设置positive为0，看你们的偏好，你可以对比一下最终结果是否一致；
- 最好还是转成得分部署吧，这个也是评分卡的优势之一。
- woebin函数转woe时做了非常多的检查，这些都比较费时间的。不过你一旦已经分好箱了，有了切割点应该转换起来非常迅速的。

**Comment by longhua8800w** [comment]
sas方便的地方是可以在图形上鼠标拖动，这个时候甚至不用关心分隔点的具体值。只看单调性和一致性就好了。而且如果要求更严格，需要把woe调成线性的。这个时候经常会各个点拖动来试探。 这个时间可能是一秒两三次。直觉到不对 就去改了。本来分箱就很累人了，如果改成全部手动输入修改分隔点，耗时还要加倍，关键是会打断直觉性的思考。我使用中印象是95%情况R远比sas好用的多但这个功能目前还是sas好用。为了实现这个我试图用shiny自己开发个替代品（鼠标拖动调节），但考虑到shiny反应速度可能会跟不上（没有完全放弃），在看julia的实现了。
我看了两边的具体逻辑的，即使设置positive为0，还是有很大不同。没信心短时间内梳理对齐参数标准让两边取得一致的结果。woe变换不只是评分卡要用，也可以作为一般特征工程的一部分，所以不一定应用在评分卡的场景，还是有一定的一般性的。

**Comment by longhua8800w** [comment]
希望早日摆脱sas的魔掌……

**Comment by ShichenXie** [comment]
关于单行的数据转换，你可以给我一个案例，我看看你是怎么部署的。
