### ISSUE TITLE
How does function `iv` calculates the information values?

### ISSUE THREAD

**Issue by Leo-Lee15** [ShichenXie/scorecard#4]
Thanks for writing such a fantastic package!

I am curious about how the function `iv()` calculates the information value for a continuous variable. Look at the source code of `iv()`:
```r
ivlist = dt[, sapply(.SD, iv_xy, label), .SDcols = x]
iv_xy = function(x, y) {
  . = DistrBad = DistrGood = bad = good = NULL

  data.table(x=x, y=y)[
    , .(good = sum(y==0), bad = sum(y==1)), keyby="x"
    ][, (c("good", "bad")) := lapply(.SD, function(x) ifelse(x==0, 0.99, x)), .SDcols = c("good", "bad")# replace 0 by 0.99 in good/bad columns
    ][, `:=`(
      DistrGood = good/sum(good), DistrBad = bad/sum(bad)
   )][, sum((DistrBad-DistrGood)*log(DistrBad/DistrGood)) ]

}
```
I am not very familiar with `data.table` package. Based on the above code, it seems that you consider every unique value as a group and count the number of "bad" and "good" in each group respectively. From this perspective, I use package `dplyr` to calculate the information value of variable `age.in.years` in dataset  `germancredit`. 
Based on the `iv()` function in  your `scorecard` package, we can obtain that the IV of variable  `age.in.years`  is 
```r
ivs <- iv(germancredit, y = "creditability")
# Warning message:
# In check_y(dt, y, positive) :
# The positive value in "creditability" was replaced by 1 and negative value by 0.
ivs[variable=="age.in.years",]
```
```r
#       variable info_value
# 1: age.in.years  0.2596514
```

While the results of my `dplyr` solution is 
```r
library(dplyr)
library(tidyr)
germancredit %>% 
  count(age.in.years, creditability) %>% 
  spread(key = creditability, value = n) %>% 
  # delete groups including only one class: "good" or "bad"
  na.omit() %>% 
  mutate(total_good = germancredit %>% 
           count(creditability) %>% 
           filter(creditability == "good") %>% 
           pull(n),
         total_bad = germancredit %>% 
           count(creditability) %>% 
           filter(creditability == "bad") %>% 
           pull(n)) %>% 
  mutate(bad_distr = bad / total_bad,
         good_distr = good / total_good,
         woe = log(bad_distr / good_distr),
         bin_iv = (bad_distr - good_distr) * woe,
         total_iv = sum(bin_iv)) 
```
```r
# A tibble: 47 x 10
   age.in.years   bad  good total_good total_bad bad_distr good_distr     woe   bin_iv total_iv
          <dbl> <int> <int>      <int>     <int>     <dbl>      <dbl>   <dbl>    <dbl>    <dbl>
 1          19.     1     1        700       300   0.00333    0.00143  0.847  0.00161     0.257
 2          20.     5     9        700       300   0.0167     0.0129   0.260  0.000989    0.257
 3          21.     5     9        700       300   0.0167     0.0129   0.260  0.000989    0.257
 4          22.    11    16        700       300   0.0367     0.0229   0.473  0.00653     0.257
 5          23.    20    28        700       300   0.0667     0.0400   0.511  0.0136      0.257
 6          24.    19    25        700       300   0.0633     0.0357   0.573  0.0158      0.257
 7          25.    19    22        700       300   0.0633     0.0314   0.701  0.0224      0.257
 8          26.    14    36        700       300   0.0467     0.0514  -0.0972 0.000463    0.257
 9          27.    13    38        700       300   0.0433     0.0543  -0.225  0.00247     0.257
10          28.    15    28        700       300   0.0500     0.0400   0.223  0.00223     0.257
# ... with 37 more rows
```

It is clear that my results are a little different from yours. Maybe it is owing to your usage of ` ifelse(x==0, 0.99, x)`? I feel very perplexed at this line of code. 

In sum, my question is 
-- How does the function `iv()` works in continuous variables?
-- If the `iv()` function does not use the optimal bins for continuous variables, are the results of the `iv()` function reliable? 

Thanks again for this awesome package. B.T.W, the slides in your website is super helpful!

**Comment by ShichenXie** [comment]
Just as you said, the `iv()` treats each unique value as a group and count the number of good and bad in each group. The difference between our results is due to you deleted the groups including only one class of good or bad. This is not reasonable since you removed some useful information. 

Usually, people might assign the information value as 0 for the groups including only one class. In my case, I replace the zeros in the class number as 0.99, which might overestimate the variable's information value. 

The information value is widely used in variable selection. We usually delete variables which iv is less than 0.02. So it's not a bad idea to overestimate the information value. 

I have modified your code, which can get the same result as `iv()`. 

```r
library(scorecard)
data("germancredit")

library(dplyr)
library(tidyr)
iv = germancredit %>% 
  group_by(age.in.years) %>% 
  summarise(good = sum(creditability=='good'), bad = sum(creditability=='bad')) %>% 
  mutate(
    good = ifelse(good ==0, 0.99, good),
    bad = ifelse(bad ==0, 0.99, bad),
  ) %>% 
  mutate(bad_distr = bad / sum(bad),
         good_distr = good / sum(good),
         woe = log(bad_distr / good_distr),
         bin_iv = (bad_distr - good_distr) * woe,
         total_iv = sum(bin_iv)) 
```

**Comment by Leo-Lee15** [comment]
Thanks your detailed reply. Your code is definitely better and cleaner. 

My thought is: 
1. use function `var_filter()` to select the variables roughly. Since we group by every unique value, the calculated IVs must be >= the IVs using optimal bins (**more bins, higher IVs**). If those overestimated IVs are smaller than 0.02, the IVs using the optimal bins must be < 0.02;
2.  use function `woebin()` to calculate the optimal bins and the corresponding IVs ;
3. based on the results of `woebin()` function, we choose the variables whose IV is larger than 0.02 as the desired variables;
4. eliminate multicollinearity : remove variables which are highly correlated and have a smaller IV;
5. fit the `GLM` model ;


Do you think my thinking is correct? Thanks!

**Comment by ShichenXie** [comment]
You are right. 
As the 4th point, you can use lasso to select variables, which have been explained in my slides. 

You can reference Refaat's book for more detailed scorecard developing process. The book is available on taobao or JD.

**Comment by Leo-Lee15** [comment]
Thanks for your guidance!

**Comment by ShichenXie** [comment]
:)
