### ISSUE TITLE
How does it identifies  breakpoints in gainstable /perf_psi ? 

### ISSUE THREAD

**Issue by anks7190** [ShichenXie/scorecard#42]
Hi , my score list contains - test and train and I want to create breakpoints based on only train data and apply those breaks points to test data .  Is it possible ?
What I have found out is , it makes breakpoints based on both the data . Isn't this wrong ?
Ideally , for PSI , the bins should be created only on the basis of train data and then we would want to see how test data is distributed on those bins and how much it has shifted.

**Comment by ShichenXie** [comment]
The issue fixed based on your suggestion. The first data is used to create breakpoints by default. You can also specify the name of data or breakpoints directly using the breaks_by argument.
Try to install the latest version on github via `devtools::install_github('shichenxie/scorecard')`. 
f9515e685cc7fecbdf4557e3bdb8c98ce1998b70

**Comment by anks7190** [comment]
Hey ShichenXie , 

I tried using the "breaks_by" switch but I couldn't make it work.
Here is how I tried -> gains_table(score = score_list, label = label_list,method="freq",breaks_by = c("test"))

It would be really helpful , if you can share some examples. 

Thanks

**Comment by ShichenXie** [comment]
There was a mistake in the code. Please try again.

**Comment by anks7190** [comment]
Hi  , the  issue of specifying "train"/"test" seems to be fixed now.
However , specifying breaks doesn't seems to  be working .
I am doing something like this - >  perf_psi(score = score_list, label = label_list,method="freq",breaks_by=c(400,500,550))

**Comment by ShichenXie** [comment]
Thanks for the feedback. Please try again.
