### ISSUE TITLE
woe value problem

### ISSUE THREAD

**Issue by longhua8800w** [ShichenXie/scorecard#43]
in recent use  we find woe_bin' s result bins woe value is not equal to log(p_bad/p_good) 

`> bins
$score1
variable        bin count  count_distr good bad    badprob        woe      bin_iv  total_iv  breaks
1:   score1    missing     1 0.0001557632    1   0 0.00000000  1.7041 254 0.001408331 0.0725454 missing
2:   score1 [-Inf,475)   401 0.0624610592  300 101 0.25187032  0.6255138 0.029977971 0.0725454     475
3:   score1  [475,515)  2191 0.3412772586 1800 391 0.17845733  0.1873414 0.012769587 0.0725454     515
4:   score1  [515,570)  3486 0.5429906542 3033 453 0.12994836 -0.1872396 0.017822342 0.0725454     570
5:   score1 [570, Inf)   341 0.0531152648  307  34 0.09970674 -0.4863114 0.010567168 0.0725454     Inf
is_special_values
1:              TRUE
2:             FALSE
3:             FALSE
4:             FALSE
5:             FALSE

> bins1$score1%>% 
  +   mutate(pg = good / sum(good), 
             +          pb = bad / sum(bad),
             +           woe1=log(pb/pg))%>%
  +   select( bin,woe,woe1)
bin        woe       woe1
1:    missing  1.7041254       -Inf
2: [-Inf,475)  0.6255138  0.6265245
3:  [475,515)  0.1873414  0.1883521
4:  [515,570) -0.1872396 -0.1862289
5: [570, Inf) -0.4863114 -0.4853007`

why this happen is there something wrong?

**Comment by ShichenXie** [comment]
你给一个可重现的案例吧，比如用自带的数据集计算一下，看看能不能出现你这个问题

**Comment by longhua8800w** [comment]
这是 我的数据集
[train.zip](https://github.com/ShichenXie/scorecard/files/5192915/train.zip)

这是我的代码
library(tidyverse)
library(scorecard)
train <- read_csv("temp/scorcard_woe_problem/train.csv")


bins <- woebin(train,y = "y")

bins$score1%>% 
  mutate(pg = good / sum(good), 
   pb = bad / sum(bad),
woe1=log(pb/pg))%>%
select( bin,woe,woe1)

问题的具体体现 就是 最后这一步 woe 和 woe1 不一致，尤其是 woe 是 -Inf的地方

**Comment by ShichenXie** [comment]
我知道了，因为你有一个分箱没有bad，scorecard包为了可计算将这个0替换为0.9了。这里的问题是你为啥能容忍没有bad的分箱

**Comment by longhua8800w** [comment]
由于变量比较多，先对满足初步要求的的 也就是没有被 var_filter干掉的变量 做单变量分析。 做法是把trian的分箱，应用到test上。 默认用的是 tree 分箱。然后看train test两边的 iv  ks 和 psi 作为进一步筛选变量的依据，并不会真用这个分箱，实际入模变量的分箱是手工做的，不会有这个问题。 数值计算中为解决下溢的问题 会把分母下溢的0替换成较小的数。这里替换成0.9是不是有点大？另外其他（非 Inf） woe值 也与woebin的结果有差异，是woebin小数点后保留位数不同导致的吗？

**Comment by longhua8800w** [comment]
？？
