### ISSUE TITLE
Use of odds0

### ISSUE THREAD

**Issue by tthuonghn** [ShichenXie/scorecard#45]
Hi,

I have a question on the default value and use of parameter odds0. 
So if I want to set a target score of 600 where the odds of good/bad = 50; does it mean I should set odds0=1/50 in the function? (I am trying to replicate this scorecard building method with your package https://towardsdatascience.com/intro-to-credit-scorecard-9afeaaa3725f).

Thanks in advance for the help.

**Comment by ShichenXie** [comment]
Yes, you are right.
