### ISSUE TITLE
The result output of gains_table needs to be added []

### ISSUE THREAD

**Issue by XianglinZhang-risker** [ShichenXie/scorecard#47]
Hello, Mr. Xie, as a risk control officer, I like your package very much, but I think this may be a small bug. The data.table obtained by gains_table must be directly output with [], otherwise the name of the output result will be printed twice In order to output, you may need to add [] to the data.table obtained at the end of the gains_table function.

**Comment by ShichenXie** [comment]
Good point. I have fixed it, you can try the latest version on Github.
