### ISSUE TITLE
scorecard function scores vs bad probablities

### ISSUE THREAD

**Issue by islander22** [ShichenXie/scorecard#48]
--

**Comment by ShichenXie** [comment]
Please provide a reproducible example. It should be caused by your own code but not the function itself.

**Comment by islander22** [comment]
card = scorecard(bins, model_1)

using that code.

may be it is doing because of the there is a variable highly correlated with that variable?

**Comment by islander22** [comment]
I tthikn your scorecard2 function solvers this. It solved when I used this function.

card2 = scorecard2(bins=bins, dt=my_data, y='TARGET',
  x= sub('_woe', '', names(coef(model_1))[-1]))

first I had used that :

card = scorecard(bins, model_1)

the POINTS trend became vice versa.

Why does it do that?

**Comment by ShichenXie** [comment]
Can you reproduce your issue with the code you provide?

**Comment by islander22** [comment]
I am using same codes in your tutorial. 

data("germancredit")

dt_f = var_filter(germancredit, "creditability")

dt_list = split_df(dt_f, ratio = 0.7, seed = 123, "creditability")

label_list = lapply(dt_list, function(x) x$creditability)

bins = woebin(dt_list$train, "creditability")

dt_woe_list = lapply(dt_list, function(x) woebin_ply(x, bins))

m1 = glm(creditability ~ ., family = binomial(), data = dt_woe_list$train)

card_m1 = scorecard(bins, m1)


Here when ı produce card_m1 in the variables which the model coefficients are NEGATIVE, ı am taking score points vice versa. 

other.debtors.or.guarantors_woe                         -0.25532

in this variable the scoring points are vice versa. (high bad probablity high score, not normal)

why does this happen?
thank you
