### ISSUE TITLE
Different IV values

### ISSUE THREAD

**Issue by seuriously** [ShichenXie/scorecard#5]
Hi,
how come the value of IV is different in function IV and woebin.
![image](https://user-images.githubusercontent.com/7880604/39185573-d5b4b6c8-47f1-11e8-924e-682367f4bdfa.png)

I notice IV is used in function var_filter thus if the value is wrong we would catch wrong variables.

I compare IV result with smbinning package and the value is closer to your woebin function.
![image](https://user-images.githubusercontent.com/7880604/39185686-3675c394-47f2-11e8-89d7-ad5efe534eb4.png)

**Comment by ShichenXie** [comment]
You are the third person asking this question. 
The `iv` function calculates the original information values which treats each value as a group. However, the total_iv in `woebin` results is information values after optimal binning. See the following example code:

```r
library(scorecard)
set.seed(100)
df = data.frame(
  x=sample(c(letters[1:6],NA),100,replace=TRUE),
  y=sample(0:1, 100, replace=TRUE)
)

iv(df,'y') 

woebin(df, 'y', breaks_list = list(x=letters[1:6])) # each value in a group, the same as iv's

woebin(df, 'y') # optimal binning
```
