### ISSUE TITLE
Problem with perf_eva density plot

### ISSUE THREAD

**Issue by ptlarsson** [ShichenXie/scorecard#54]
Shichen

Sometimes the density plot in the perf_eva function comes out with the y-axis not properly scaled resulting in the lines not showing.

See below for sample code and data to recreate the problem and the resulting plot. I have tested using scorecard version 0.2.4 on Windows and version 0.3.0 on Linux, same result both times.

Thanks

Tomas

require(dplyr)
require(scorecard)
x <- read.csv("M7_WOE Binomial_632.csv")
xx <- x %>% filter(modelsample=="Hold out sample")
perf_eva(xx$modelscore,xx$Churn,show_plot = "density")

[M7_WOE Binomial_632.csv](https://github.com/ShichenXie/scorecard/files/6759247/M7_WOE.Binomial_632.csv)

[Rplot.pdf](https://github.com/ShichenXie/scorecard/files/6759252/Rplot.pdf)

**Comment by ShichenXie** [comment]
It's strange. I can't reproduce your issue using scorecard version 0.3.3 on ubuntu. The result is as following. Please update your package and try again. 

![image](https://user-images.githubusercontent.com/15758951/124371149-86927780-dcb1-11eb-8bb4-76784eddc3e2.png)

**Comment by ptlarsson** [comment]
Yes, upgrading to 0.3.3 solved it.

Thanks.
