### ISSUE TITLE
Formulas

### ISSUE THREAD

**Issue by alikt001** [ShichenXie/scorecard#56]
Hi. Hope you are well. 
I got stuck while computing various calculations manually to cross check the results obtained using your library. Therefore, I would like you to share the exact formulas that you've used to perform following calculations:
- baseline score
- score against each bin of a variable

Looking forward to your response. Thanks in advance!

**Comment by ShichenXie** [comment]
Well, it's nothing different. You can read the reference the `Refaat, M. (2011, ISBN: 9781447511199). Credit Risk Scorecard: 
  Development and Implementation Using SAS. ` for more details.
