### ISSUE TITLE
关于woebin等频分箱报错

### ISSUE THREAD

**Issue by holdenyau** [ShichenXie/scorecard#57]
谢老师好，我用您例子中的代码运行时，发现当分箱方式为‘freq’时报了以下错误，而用默认分箱方式时则不会报错；且当y值设为null时，也会把报错，麻烦您给予解答，感谢！

> data(germancredit)
> numeric_cols = c("duration.in.month", "credit.amount",
                  "installment.rate.in.percentage.of.disposable.income", "present.residence.since",
                  "age.in.years", "number.of.existing.credits.at.this.bank",
                  "number.of.people.being.liable.to.provide.maintenance.for")
> bins_freq  = woebin(germancredit, y="creditability", x=numeric_cols, method="freq")
[INFO] creating woe binning ... 
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: Error in brk_numx_init(brkp, unique_xvalue) : 
  'list' object cannot be coerced to type 'double'

> bins_freq_noy  = woebin(germancredit, y=NULL, x=numeric_cols)
[INFO] creating woe binning ... 
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: Error in brk_numx_init(brkp, unique_xvalue) : 
  'list' object cannot be coerced to type 'double'

**Comment by ShichenXie** [comment]
这个好像是bug，我回头看看啊

**Comment by ShichenXie** [comment]
修复了，安装github上的最新版本试试看
