### ISSUE TITLE
Gini with to = 'bin'

### ISSUE THREAD

**Issue by naitsimp** [ShichenXie/scorecard#58]
Hello,

I am trying to get the GRP Gini coefficient.
**Error arises here:**
`score_grp.list <- lapply(data_f.list, function(x) scorecard_ply(x, scorecard_grp.scm)) `
**Error:**
``Error in `[.data.table`(dt, , x_i, with = FALSE) : 
  column(s) not found: NA``

I think this is the Source of the Problem:
`data_grp.list = lapply(data_f.list, function(x) woebin_ply(x, bins.list, to = 'bin'))`
If i remove ` to = 'bin'` I get my WOE Gini without a Problem, but when I want to get my GRP Gini with `to = 'bin'` I run into Problems.
**data_grp.list:**
![image](https://user-images.githubusercontent.com/37888708/143454904-9ec7ed7d-d04b-4236-aea7-acb4a39be93e.png)
The Values are not correct. 

In comparison when I use `to = 'woe'` (the default):
`data_woe.list <- lapply(data_f.list, function(x) woebin_ply(x, bins.list))`
**data_woe.list:**
![image](https://user-images.githubusercontent.com/37888708/143455205-b8829b71-bf04-4674-a3aa-be81f26f6e28.png)

My Code:
````{r}
library(scorecard)
data("germancredit")

data.df <- germancredit[,c("creditability",
                           "credit.amount", "duration.in.month", "credit.history",
                           "purpose", "property", "savings.account.and.bonds")]
data_f.df <- var_filter(data.df, "creditability")
data_f.list <- split_df(data_f.df,"creditability",
                        ratio = c(0.75,0.25), name_dfs=c("train","test"))
default.list = lapply(data_f.list, function(x) x$creditability)
bins.list = woebin(data_f.list$train, "creditability")
breaks.list = list(
  credit.amount = c("1400", "4000", "5000", "10000"), 
  duration.in.month = NULL, 
  credit.history = NULL, 
  purpose = NULL, 
  property = NULL, 
  savings.account.and.bonds = NULL)
bins.list = woebin(data_f.list$train, "creditability", breaks_list = breaks.list)

data_grp.list = lapply(data_f.list, function(x) woebin_ply(x, bins.list, to = 'bin'))

data_grp.glm <- glm(creditability ~ .,
                    family = binomial(),
                    data = data_grp.list$train)

scorecard_grp.scm <- scorecard(bins.list, data_grp.glm)

score_grp.list <- lapply(data_f.list, function(x) scorecard_ply(x, scorecard_grp.scm)) 

gini_grp <- perf_eva(pred = score_grp.list,
                    label = default.list,
                    binomial_metric = c("gini"),
                    show_plot= FALSE)

gini_grp$binomial_metric$test$Gini
````

Any ideas how I can solve this Problem?

Thanks

**Comment by ShichenXie** [comment]
Why you transfer the original values into bins. The bin values are character, which can't used as input in glm model.

**Comment by ShichenXie** [comment]
Why you transfer the original values into bins. The bin values are character, which can't used as input in glm model.
