### ISSUE TITLE
Scorecard2 issue with probability set to TRUE

### ISSUE THREAD

**Issue by Alexa2371a** [ShichenXie/scorecard#59]
if scorecard2 probability is set to true
card2 = scorecard2(bins=bins, dt=germancredit, y='creditability',
                   x=sub('_woe', '', names(coef(m))[-1]), basepoints_eq0 = TRUE,return_prob = TRUE)
the following error is produced when scorecard_ply  is used after:
score12 = scorecard_ply(germancredit, card2)
Error in setDT(card) : 
  All elements in argument 'x' to 'setDT' must be of same length, but the profile of input lengths (length:frequency) is: [13:1, 1000:1]
The first entry with fewer than 1000 entries is 1

When probability is not used, then it works fine

**Comment by ShichenXie** [comment]
If the parameter 'return_prob' is TRUE, the result of scorecard2 is a list of card and probability.  Please provide the card only in the scorecard_ply function,  `score12 = scorecard_ply(germancredit, card2$card)`.

**Comment by Alexa2371a** [comment]
thank you
