### ISSUE TITLE
Already Exporting Variable

### ISSUE THREAD

**Issue by Ouster22** [ShichenXie/scorecard#6]
Hi and thanks for your useful package.  I get the below warning message when running with my own data.  The final scorecard seems fine so at the moment I am ignoring the message, but what is the root cause?

> bins = woebin(dt_s, y="IsDef", no_cores = 8)
Warning message:
In e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): dt, xs, y, breaks_list, min_perc_fine_bin, stop_limit, max_num_bin

**Comment by ShichenXie** [comment]
I also got this warning message in `woebin` function when using multiple cores. This warning doesn't affect the final results. It seems some thing wrong in the setting of parallel computation. You can just ignore it at this moment. I'll try to fix it in the future.

**Comment by ShichenXie** [comment]
This issue seems be fixed in the current version.
