### ISSUE TITLE
question min and max score

### ISSUE THREAD

**Issue by Alexa2371a** [ShichenXie/scorecard#60]
Hi
how can I set minimum (300) and maximum (850) score using scorecard function?

scorecard(bins, model, points0 = 600, odds0 = 1/19, pdo = 50, basepoints_eq0 = FALSE, digits = 0)

and how can I access confusion matrix?

**Comment by ShichenXie** [comment]
You can't directly setting the score range using the scorecard function. Why you need to set the score range. 
The perf_eva function provides confusion matrix.
