### ISSUE TITLE
Information Value from scorecard::iv() is not equal to Information value from scorecard::woebin()

### ISSUE THREAD

**Issue by L-1996-G** [ShichenXie/scorecard#61]
Hi, 

I try to identify significant covariates for Probability of Default model. I use `scorecard::woebin()` and `woe_plot() ` function to calculate woe and iv for numeric variables. Then I use `iv()` function to calculate IV for those variables. Information Values from these two methods are very different from each others (IV on the top of `woe_plot` is less than 5%, while IV from `iv()` function is more than 50%). What is the reason of this?

**Comment by ShichenXie** [comment]
The woebin function calculates info-value after binning, and iv function calculates info-value without binning . The woebin function actually calls the iv function to do the calculation.

**Comment by L-1996-G** [comment]
@ShichenXie Thank you for answering. Which of them should I use during variable selection process? If I based on woebin, variable had not even moderate explanatory power, while using iv function shows that the same variable has strong explanatory power.

**Comment by ShichenXie** [comment]
You can use the var_filter function for the initial variable selection, which includes iv, identical rate and missing rate.
