### ISSUE TITLE
分箱区间问题

### ISSUE THREAD

**Issue by skq642877841** [ShichenXie/scorecard#62]
首先我在包版本0.3.4的时候 options(scorecard.bin_close_right=TRUE) 后单个变量分箱用右闭是没有问题的，但是woebin不设置x参数批量分箱时结果没有右闭。然后我怀疑是我版本较低，可能高版本会解决这个bug，所以我更新了scorecard版本至0.3.6，然后发现右闭的设置无论是单变量分箱还是批量分箱都不起作用了...

例子用的example里的示例...

**Comment by skq642877841** [comment]
![image](https://user-images.githubusercontent.com/76772520/167113651-da250e87-3f27-451b-b6b7-bb62c1cfb25e.png)

**Comment by ShichenXie** [comment]
这个bug修复了，谢谢反馈。请更新到github上的最新版试试。

**Comment by skq642877841** [comment]
谢谢，可以了...
