### ISSUE TITLE
woebin 指定breaklist时有问题

### ISSUE THREAD

**Issue by skq642877841** [ShichenXie/scorecard#63]
woebin，数值型变量指定break_list含有分割点0的时候，结果貌似会把0剔除了的。
下图中 我首先用了options(scorecard.bin_close_right = TRUE) 指定右闭区间，然后指定break_list中只用0分箱，期望得到的分箱结果为<=0  \  >0  \Missing  三箱，结果却不对。

![image](https://user-images.githubusercontent.com/76772520/177097663-369fcf15-cecd-4ff2-8f93-94ee3f51bc0f.png)

**Comment by ShichenXie** [comment]
可能是因为占比太少，所以合并了

**Comment by skq642877841** [comment]
应该不是的，占比如下：
![image](https://user-images.githubusercontent.com/76772520/177101266-706f3bcb-ae35-45d9-9906-7d177997eafe.png)

**Comment by ShichenXie** [comment]
你看看有没有办法弄一个可重复的例子，比如用包里自带的数据

**Comment by skq642877841** [comment]
用该包自有的数据 ，找了一个变量 age.in.years ，先用自由分箱结果cuts为25、27、34、36，然后我把这个变量<=25的数值都改为0 ，然后用breaks_list设定切分点为  c(0,27,34,36,Inf) ，结果<=0分箱的组也是没有出现...

![image](https://user-images.githubusercontent.com/76772520/177104989-11c66088-75a5-4169-b728-a336d4b92ec5.png)

**Comment by ShichenXie** [comment]
你安装GitHub上面的版本试试，应该解决了。

**Comment by skq642877841** [comment]
老师您好，我用install_github 更新了scorecard包，目前包的版本是0.3.7.999
![image](https://user-images.githubusercontent.com/76772520/177728409-906a7643-f7f4-44cf-b586-c141b77bd114.png)

但是好像结果依旧有问题，望知悉。。


![image](https://user-images.githubusercontent.com/76772520/177727858-e627e802-c2c0-4f31-be2b-a338169cb874.png)

**Comment by skq642877841** [comment]
另  这个情况在options(scorecard.bin_close_right = F) 时不会出问题，而在options(scorecard.bin_close_right = T) 的时候，连续性变量用最小值做切分点的时候都不行（与是否用0切分无关）

**Comment by ShichenXie** [comment]
这个是平行计算的问题，藏的比较深。应该已经解决了，你再试试看。

**Comment by ShichenXie** [comment]
这个是并行计算时出现的问题，藏的比较深。应该已经解决了，你再试试看。

**Comment by skq642877841** [comment]
结果跟昨天的一样...

![image](https://user-images.githubusercontent.com/76772520/177900095-63f6cde4-8b90-49cd-94eb-9aeeffdf0b1b.png)

**Comment by ShichenXie** [comment]
你没更新成功

**Comment by skq642877841** [comment]
结果依旧，我试了两种方法，一种是devtools::install_github("ShichenXie/scorecard") 另一种是网页下载下来ZIP包用 devtools::
devtools::install_local的方法安装，结果包的版本号依旧是0.3.7.999 ，但是显示built时间都是 2022-07-08 02:50:35 UTC;

![image](https://user-images.githubusercontent.com/76772520/177908159-4e0f6a6b-b70a-4dd2-99c3-01a576d34d56.png)

**Comment by ShichenXie** [comment]
你再试试，我昨天忘记上传了

**Comment by skq642877841** [comment]
谢谢，刚更新试了下，可以了，多谢！
