### ISSUE TITLE
Line plot for woebin_adj with line_value = "woe" resets to positive probability after adjusting breaks

### ISSUE THREAD

**Issue by radical6** [ShichenXie/scorecard#64]
The blue line in the plots after adjusting the breaks for a variable resets to positive probability.

**Comment by radical6** [comment]
also this warning message comes up when using woebin_adj in the latest version (0.3.8)

> In sprintf("[INFO] The option bin_close_right was set to %s.\n",  ... :
>   one argument not used by format '[INFO] The option bin_close_right was set to %s.

**Comment by ShichenXie** [comment]
> The blue line in the plots after adjusting the breaks for a variable resets to positive probability.

I can't understand what refers to ' resets to positive probability'. Please provide a reproducible example. 


> also this warning message comes up when using woebin_adj in the latest version (0.3.8)

You can ignore this warning, it would't affect the results. It will be fixed soon.

**Comment by radical6** [comment]
Using woebin_adj with line_value = "woe" in RStudio, the first plot shows the woe line plot:
![image](https://user-images.githubusercontent.com/27696764/179282758-a98359b2-19da-47b7-b00f-a34783c7d16c.png)

But after adjusting the breaks, the line plot changes to posprob:
![image](https://user-images.githubusercontent.com/27696764/179283027-f10898b2-1860-4d7b-896d-1c8dc4f868d9.png)

**Comment by ShichenXie** [comment]
The bug should be fixed. Please upgrade to the latest version on Github and try again.

**Comment by radical6** [comment]
It is indeed fixed, thanks!
