### ISSUE TITLE
Native pipe |> requires R >=4.1

### ISSUE THREAD

**Issue by philip-khor** [ShichenXie/scorecard#65]
Checks failing for var_filter due to use of native pipe for R<4.1: https://github.com/conda-forge/r-scorecard-feedstock/pull/11/checks?check_run_id=7489531965

https://github.com/ShichenXie/scorecard/blob/d3e78e245b677f64408d8ad5ed464caa306b84c1/R/var_filter.R#L111

**Comment by ShichenXie** [comment]
Thanks. The |> operator was removed.
