### ISSUE TITLE
Cannot install.packages("scorecard") on windows

### ISSUE THREAD

**Issue by J-sephB-lt-n** [ShichenXie/scorecard#66]
install.packages("scorecard")

  * installing *source* package 'scorecard' ...
  ** package 'scorecard' successfully unpacked and MD5 sums checked
  ** using staged installation
  ** R
  Error in parse(outFile) : 
    C:/Users/jbolton/AppData/Local/Temp/RtmpaepnGS/R.INSTALLb74c541c738/scorecard/R/var_filter.R:111:97: unexpected '>'
  110: 
  111:     lrx_rm = lapply(c(lrx_filter1$xrm, lrx_filter2$xrm), function(x) data.table(variable = x)) |>
                                                                                                       ^
  ERROR: unable to collate and parse R files for package 'scorecard'
  * removing 'C:/Users/jbolton/Documents/R/win-library/4.0/scorecard'
  Warning in install.packages :
    installation of package ‘scorecard’ had non-zero exit status

**Comment by ShichenXie** [comment]
please upgrade your R to 4.1 or later. The source code used a pip operator ‘|>’, which is only available for R >= 4.1.

**Comment by J-sephB-lt-n** [comment]
Thanks for the lightning fast reply. 

Sorry to waste your time! 

Love your package <3 thank you
