### ISSUE TITLE
Fail to install - 0.3.9

### ISSUE THREAD

**Issue by EVON999** [ShichenXie/scorecard#67]
Error in parse(outFile) : 
  /private/var/folders/jz/m30s89fx3lnbf2by_wqb1vyh0000gp/T/RtmpGoCA5z/R.INSTALL17fff428adaa1/scorecard/R/var_filter.R:111:97: 意外的'>'

lrx_rm = lapply(c(lrx_filter1$xrm, lrx_filter2$xrm), function(x) data.table(variable = x)) |>

------log-------
installing the source package ‘scorecard’

试开URL’https://cran.rstudio.com/src/contrib/scorecard_0.3.9.tar.gz'
Content type 'application/x-gzip' length 92814 bytes (90 KB)
==================================================
downloaded 90 KB

* installing *source* package ‘scorecard’ ...
** 成功将‘scorecard’程序包解包并MD5和检查
** using staged installation
** R
Error in parse(outFile) : 
  /private/var/folders/jz/m30s89fx3lnbf2by_wqb1vyh0000gp/T/RtmpGoCA5z/R.INSTALL17fff428adaa1/scorecard/R/var_filter.R:111:97: 意外的'>'
110: 
111:     lrx_rm = lapply(c(lrx_filter1$xrm, lrx_filter2$xrm), function(x) data.table(variable = x)) |>
                                                                                                     ^
ERROR: unable to collate and parse R files for package ‘scorecard’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/scorecard’
Warning in install.packages :
  installation of package ‘scorecard’ had non-zero exit status

**Comment by EVON999** [comment]
@ShichenXie

**Comment by ShichenXie** [comment]
scorecard 的 0.3.9 版源代码中使用了 |>，需要 R >= 4.1 才支持。github上面的最新版代码已经删除这个运算符了。所以你可以升级 R 版本 >= 4.1，或者安装github上面最新版的包。
