### ISSUE TITLE
Definition of offset in the scorecard function

### ISSUE THREAD

**Issue by MikaellaKats** [ShichenXie/scorecard#68]
Hello,

I just have a quick question on the definition of a within the function ab that is used by the scorecard function to produce the scores. As I understand a refers to the offset. Shouldn't the definition of a be "a = points0 - b*log(odds0)" instead of "a = points0 + b*log(odds0)".

Thank you

**Comment by ShichenXie** [comment]
These two formulas are the same. The only difference is the sign of b are opposite.
