### ISSUE TITLE
Is there any way to export the scorecard to PMML?

### ISSUE THREAD

**Issue by denmase** [ShichenXie/scorecard#69]
Hi @ShichenXie,

I'd like to ask whether there's a way to export the scorecard to PMML. I know I can export `glm/lm` object into PMML using either `pmml `or `r2pmml` package, however both require the object to be a type of "`list`" and class of "glm/lm", because both complained that **the object is not glm**. Or probably I did it wrongly?

And other thing, is there a way to set adverse reason codes for the scorecard?

Thanks in advance.
Regards,
Agung

**Comment by ShichenXie** [comment]
It is still on the package scorecard's to-do list. Just as you said, you can export the glm object into PMML using the `pmml` package. 

```library(pmml)
data(iris)
mod <- glm(Sepal.Length ~ ., data = iris, family = "gaussian")
mod_pmml <- pmml(mod)
```

**Comment by denmase** [comment]
Great, thanks. 

Yes, I can export the `glm` object just fine, however since it's not the final scorecard, so we can't really use the PMML. I have similar problem in Python where the package I use is not supported by either `sklearn2pmml` or `nyoka`. What I'm doing now is I dump the scorecard object into JSON and translate it to PMML using a simple C# program I wrote, but it's way far away from a complete solution which can cover complete specification of PMML.

Thank you for putting it on the package to-do list.

Cheers

**Comment by ShichenXie** [comment]
Please upgrade scorecard package to the latest version on GitHub via `devtools::install_github('shichenxie/scorecard')`.  The new function `scorecard_pmml` supports to export scorecard into pmml file. Since I don't have an environment to test the pmml file, please let me known if there is any bug.

**Comment by denmase** [comment]
Wow thank you. I'll be testing it from now on. Syntax-wise, I did a quick look into generated PMML and noticed something that I want to ask you about.

```   
      <Characteristic name="other.installment.plansScore">
        <Attribute partialScore="-26">
          <SimplePredicate field="other.installment.plans" operator="equal" value="bank"/>
        </Attribute>
        <Attribute partialScore="-26">
          <SimplePredicate field="other.installment.plans" operator="equal" value="stores"/>
        </Attribute>
        <Attribute partialScore="7">
          <SimplePredicate field="other.installment.plans" operator="equal" value="none"/>
        </Attribute>
      </Characteristic>

      <Characteristic name="purposeScore">
        <Attribute partialScore="53">
          <SimplePredicate field="purpose" operator="equal" value="retraining"/>
        </Attribute>
        <Attribute partialScore="53">
          <SimplePredicate field="purpose" operator="equal" value="car (used)"/>
        </Attribute>
        <Attribute partialScore="27">
          <SimplePredicate field="purpose" operator="equal" value="radio/television"/>
        </Attribute>
        <Attribute partialScore="-18">
          <SimplePredicate field="purpose" operator="equal" value="furniture/equipment"/>
        </Attribute>
        <Attribute partialScore="-18">
          <SimplePredicate field="purpose" operator="equal" value="domestic appliances"/>
        </Attribute>
        <Attribute partialScore="-18">
          <SimplePredicate field="purpose" operator="equal" value="business"/>
        </Attribute>
        <Attribute partialScore="-18">
          <SimplePredicate field="purpose" operator="equal" value="repairs"/>
        </Attribute>
        <Attribute partialScore="-18">
          <SimplePredicate field="purpose" operator="equal" value="car (new)"/>
        </Attribute>
        <Attribute partialScore="-18">
          <SimplePredicate field="purpose" operator="equal" value="others"/>
        </Attribute>
        <Attribute partialScore="-18">
          <SimplePredicate field="purpose" operator="equal" value="education"/>
        </Attribute>
      </Characteristic>
```
I'd like to ask you the reason why you used `SimplePredicate` for bins which are arrays, instead of using `SimpleSetPredicate` with `Array`. For example:
```
$purpose
                                                                                            breaks is_special_values points
1:                                                                         retraining%,%car (used)             FALSE     53
2:                                                                                radio/television             FALSE     27
3: furniture/equipment%,%domestic appliances%,%business%,%repairs%,%car (new)%,%others%,%education             FALSE    -18


$other.installment.plans
                  variable           bin count count_distr neg pos   posprob        woe     bin_iv   total_iv        breaks is_special_values points
1: other.installment.plans bank%,%stores   186       0.186 110  76 0.4086022  0.4775508 0.04593584 0.05759207 bank%,%stores             FALSE    -26
2: other.installment.plans          none   814       0.814 590 224 0.2751843 -0.1211786 0.01165623 0.05759207          none             FALSE      7

```

It can work, but won't it confuse the user (i.e., a bit "misleading', as these are actually belong to the same bin, but represented as if it was separate bin, albeit the same score)? And also, if you decide to implement adverse reason codes, these `SimplePredicate` nodes will share the same reason codes.

Functionality-wise, I'll do some testing and report back.

Thank you again for your effort and this wonderful package.

Cheers

**Comment by ShichenXie** [comment]
It seems the `SimpleSetPredicate` doesn't provided in pmml v4.4. Please read the website https://dmg.org/pmml/v4-4/Scorecard.html.  If you have any references for `SimpleSetPredicate`, please share with me. Thanks.

**Comment by denmase** [comment]
Hi,
Although it wasn't specified in PMML 4.4 scorecard specification page, if you scroll down to the attribute section, there is this

> PREDICATE: The condition upon which the mapping between input attribute and partial score takes place. For more details on PREDICATE see the section on predicates in [TreeModel](https://dmg.org/pmml/v4-4/TreeModel.html) for an explanation on how predicates are described and evaluated. In scorecard models, all the predicates defining the Attributes for a particular Characteristic must all reference a single field.

> <xs:element name="Attribute">
>   <xs:complexType>
>     <xs:sequence>
>       <xs:element ref="[Extension](https://dmg.org/pmml/v4-4/GeneralStructure.html#xsdElement_Extension)" minOccurs="0" maxOccurs="unbounded"/>
>       <xs:group ref="[PREDICATE](https://dmg.org/pmml/v4-4/TreeModel.html#xsdGroup_PREDICATE)"/>
>       <xs:element ref="[ComplexPartialScore](https://dmg.org/pmml/v4-4/Scorecard.html#xsdElement_ComplexPartialScore)" minOccurs="0"/>        
>     </xs:sequence>
>     <xs:attribute name="reasonCode" type="xs:string"/>
>     <xs:attribute name="partialScore" type="[NUMBER](https://dmg.org/pmml/v4-4/GeneralStructure.html#xsdType_NUMBER)" use="optional"/>
>   </xs:complexType>
> </xs:element>
> 

If you open the link (TreeModel), `SimpleSetPredicate` is one of the options for `Attribute`

> <xs:group name="PREDICATE">
>   <xs:choice>
>     <xs:element ref="[SimplePredicate](https://dmg.org/pmml/v4-4/TreeModel.html#xsdElement_SimplePredicate)"/>
>     <xs:element ref="[CompoundPredicate](https://dmg.org/pmml/v4-4/TreeModel.html#xsdElement_CompoundPredicate)"/>
>     <xs:element ref="[SimpleSetPredicate](https://dmg.org/pmml/v4-4/TreeModel.html#xsdElement_SimpleSetPredicate)"/>
>     <xs:element ref="[True](https://dmg.org/pmml/v4-4/TreeModel.html#xsdElement_True)"/>
>     <xs:element ref="[False](https://dmg.org/pmml/v4-4/TreeModel.html#xsdElement_False)"/>
>   </xs:choice>
> </xs:group> 

Hope this clarifies. Thank you.

**Comment by ShichenXie** [comment]
I have read the TreeModel page, but still don't known how to adopt it to scorecard. Anyway, the SimplePredicate is enough to support scorecard in pmml format.

**Comment by denmase** [comment]
That's okay, anyway thanks for the support.

This is a sample of `SimpleSetPredicate'.

```
      <Characteristic name="Saving accounts">
        <Attribute reasonCode="R03A01" partialScore="158.7015145455">
          <SimpleSetPredicate field="Saving accounts" booleanOperator="isIn">
            <Array n="2" type="string">rich &amp;quot;quite rich&amp;quot;</Array>
          </SimpleSetPredicate>
        </Attribute>
        <Attribute reasonCode="R03A02" partialScore="99.7016888117">
          <SimplePredicate field="Saving accounts" operator="equal" value="moderate" />
        </Attribute>
        <Attribute reasonCode="R03A03" partialScore="91.943279343">
          <SimplePredicate field="Saving accounts" operator="equal" value="little" />
        </Attribute>
        <Attribute reasonCode="R03A04" partialScore="149.3696236669">
          <SimplePredicate field="Saving accounts" operator="isMissing" />
        </Attribute>
      </Characteristic>
```

Since I was using C# by parsing JSON file with JSON.net, all I needed to do was to convert `JArray` to `SimpleSetPredicate` with `Array`.
