### ISSUE TITLE
Woe and points do not follow the same pattern

### ISSUE THREAD

**Issue by Alexa2371a** [ShichenXie/scorecard#71]
Hello,

I have an issue with one variable that does not behave in an expected way regarding points.
For all variables where WOE is monotonically decreasing, points go up.
For other variables where WOE is monotonically increasing, points go down.
However for one variable (w_dscr), WOE is monotonically decreasing but points go down, which is not as expected.
Points should go up (the higher the value of the variable the better).

Bins var is set as:
bins_var <- woebin(df_train_aic, y = "Default", no_cores = 20, positive = "Default|1",
                   breaks_list = breaks_list)

maybe I should also point out that for the disputed variable sign of the coefficient in log.regression is negative (while for other variables is positive)

[my_card_first_model_1a.xlsx](https://github.com/ShichenXie/scorecard/files/10386528/my_card_first_model_1a.xlsx)

**Comment by ShichenXie** [comment]
中国人么

**Comment by ShichenXie** [comment]
The coefficients of logistic regression model should be positive, if the variables have been transformed into woe values. The variables with negative coefficients might facing multicollinearity issues. You can calculate the VIF to identify the collinearity among variables.

**Comment by Alexa2371a** [comment]
Yes you are right. the possibility is to do constrained log regression and enforce the coefficient to be positive. Thank you.
