### ISSUE TITLE
Function error

### ISSUE THREAD

**Issue by Pinkmots** [ShichenXie/scorecard#72]
![scorecard](https://github.com/ShichenXie/scorecard/assets/109324906/0829e1b5-41fb-4bff-8b8d-de9be0712e96)

**Comment by Pinkmots** [comment]
还有一个地方，dt_bin = woebin_ply(dt_f, bins, to = "bin"),
![image](https://github.com/ShichenXie/scorecard/assets/109324906/00567f61-2214-44b9-9373-80b2cf2680eb)
这个参数设置为 to = "bin" 后，与后面的函数冲突了
![image](https://github.com/ShichenXie/scorecard/assets/109324906/60668f66-3a6e-4da0-91c0-a95a7e89bbe6)
导致删除出错
![image](https://github.com/ShichenXie/scorecard/assets/109324906/a0e64d8b-d272-432b-8c9d-5dd12dff9b60)
![image](https://github.com/ShichenXie/scorecard/assets/109324906/e4b60ff4-9ff3-4848-ab86-d4822fa03609)
会遗留一个bin.1的列

**Comment by ShichenXie** [comment]
给一个可重现的代码

**Comment by Pinkmots** [comment]
data("germancredit")
dt_f = var_filter(germancredit, y="creditability")

第一个：我看stop_limit可以使用list来输入参数
bins = woebin(dt_f, y="creditability",stop_limit = list(age.in.years = 0.3) )
结果是
Error in names(object) <- nm : 
  'names' attribute [13] must be the same length as the vector [2]
应该就是我第一张图的woebin里面check_stop_limit（）的函数错了

第二个：分箱后，想要使用woebin_ply（）来输出bins形式的原始数据
bins = woebin(dt_f, y="creditability")
dt_bin = woebin_ply(dt_f, bins, to = "bin")
colnames(dt_bin)
colnames(dt_f)

![image](https://github.com/ShichenXie/scorecard/assets/109324906/6e1935c3-8e12-43d4-8eea-dff25b0427c3)

![image](https://github.com/ShichenXie/scorecard/assets/109324906/3d00839e-561e-41f5-a95d-9a88ed3bde13)

**Comment by ShichenXie** [comment]
这两个参数我很少用。已经修复了，谢谢反馈。

**Comment by Pinkmots** [comment]
谢谢
