### ISSUE TITLE
Let we choose whether to let the missing value be a separate bin

### ISSUE THREAD

**Issue by Blanket58** [ShichenXie/scorecard#73]
The param `missing_join` can only be `left` or `right`, is there any way to force the missing value to be in a separate bin?

**Comment by ShichenXie** [comment]
该功能只有缺失值占比低于阈值5%时才会生效。如果缺失值占比高于阈值，就是单独一箱。对于缺失值较小时，单独一箱，对应的woe值可能没有代表性。

**Comment by ShichenXie** [comment]
missing_join 参数默认值修改为NULL了，即缺失默认为单独一箱。你升级到github上面的版本试试看。

**Comment by Blanket58** [comment]
感谢🙏
