### ISSUE TITLE
回归系数为负数时，scorecard输出特征评分项符号错误

### ISSUE THREAD

**Issue by zengke403** [ShichenXie/scorecard#8]
ShichenXie，您好。我英文不够好，但愿您能看懂中文。
首先非常感谢您开发的scorecard包,这里我报告下我遇到的一个问题：
当logit回归非截距系数为负时，输出评分卡评分项的符号有问题。
我使用R版本的scorecard_0.19。

具体:
TD_CREDITSCORE的回归权重为-0.5396,且odds0 =1/19，points=600,pdo=50

1 | variable | bin | woe | points | count | count_distr | good | bad | badprob | bin_iv | total_iv | breaks | is_special_values
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
33 | TD_CREDITSCORE | missing | 0.250670111 | 10 | 509 | 0.14753623 | 434 | 75 | 0.14734774 | 1.019171e-02 | 0.09441740 | missing | FALSE
34 | TD_CREDITSCORE | [-Inf,25) | -0.292529584 | -11 | 1721 | 0.49884058 | 1564 | 157 | 0.09122603 | 3.815798e-02 | 0.09441740 | 25 | FALSE
35 | TD_CREDITSCORE | [25,35) | 0.001571926 | 0 | 716 | 0.20753623 | 631 | 85 | 0.11871508 | 5.131192e-07 | 0.09441740 | 35 | FALSE
36 | TD_CREDITSCORE | [35,50) | 0.465781491 | 18 | 357 | 0.10347826 | 294 | 63 | 0.17647059 | 2.671513e-02 | 0.09441740 | 50 | FALSE
37 | TD_CREDITSCORE | [50, Inf) | 0.602837737 | 23 | 147 | 0.04260870 | 118 | 29 | 0.19727891 | 1.935207e-02 | 0.09441740 | Inf | FALSE

上表是scorecard输出结果，经过手工计算发现points符号有问题

**Comment by ShichenXie** [comment]
你的计算公式是什么？概率转评分的方法可以看一下http://shichen.name/scorecard/   右上角的slides

**Comment by zengke403** [comment]
嗯你说的没有问题，这个不是bug，谢谢。你可以关闭这个报告了

```
Pdo=50
beta=-0.53961
B=Pdo/log(2)
woe=c(0.250670111,
      -0.292529584,
      0.001571926,
      0.465781491,
      0.602837737)

-B*beta*woe
```
输出:
```
[1]   9.75724221 -11.38660686   0.06118664  18.13037385  23.46523800
```
