### ISSUE TITLE
Error in setDT(dt) 

### ISSUE THREAD

**Issue by farhanrezaa** [ShichenXie/scorecard#9]

**Comment by ShichenXie** [comment]
Please give me a reproducible code. 
`setDT` is a function in the package `data.table`, which is set a dataframe into datatable.

**Comment by farhanrezaa** [comment]
No worry about that. It is actually my fault. Thank you very much for
helping me.
Anyway, can you explain to me how "iv" function works? Because the
information value I get from that function is different from manual
calculation.

Thank you very much.

**Comment by ShichenXie** [comment]
The formula should be the same as yours.  In `scorecard` package, information value is calculated with the following treatments. 
(1) The `iv` function treats each value as a group. 
(2) If you have a group that has zero good or bad label, zero will replaced by 0.99.

**Comment by farhanrezaa** [comment]
Thank you very much.

I want to ask last question. What is the consideration in grouping the
factor when using "woebin" function? Because for some categorical variable
the IV when using "iv" function are higher than the IV after using "woebin"
function.

Thank you very much once again.

**Comment by ShichenXie** [comment]
There are many people asked this question. Try to find the answer by yourself.

**Comment by farhanrezaa** [comment]
Thank you very much
